services:
  app:
    container_name: ingestion-engine-app
    image: ingestion-engine-david-ferrer:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JFROG_XYLEM_PYPI_USER: "${JFROG_XYLEM_PYPI_USER}"
        JFROG_XYLEM_PYPI_TOKEN: "${JFROG_XYLEM_PYPI_TOKEN}"
        NEXUS_PYPI_USER: "${NEXUS_PYPI_USER}"
        NEXUS_PYPI_TOKEN: "${NEXUS_PYPI_TOKEN}"
    environment:
        JFROG_XYLEM_PYPI_USER: "${JFROG_XYLEM_PYPI_USER}"
        JFROG_XYLEM_PYPI_TOKEN: "${JFROG_XYLEM_PYPI_TOKEN}"
        NEXUS_PYPI_USER: "${NEXUS_PYPI_USER}"
        NEXUS_PYPI_TOKEN: "${NEXUS_PYPI_TOKEN}"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/_template_core/docker/scripts
      - venv_data:/venv
    env_file:
      - config.env
  
  postgres:
    image: postgis/postgis:16-3.5
    container_name: ingestion-engine-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: water_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  venv_data:
  postgres_data: