name: ingestion-engine

services:
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: ingestion-engine-airflow
    command: standalone
    ports:
      - "8081:8080"
    env_file:
      - config.env
    volumes:
      - airflow_data:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ingestion-network
    restart: unless-stopped

networks:
  ingestion-network:
    name: ingestion-network

volumes:
  - airflow_data:/opt/airflow