available_environments:
  - <ENVIRONMENT_1>
  - <ENVIRONMENT_2>

source:
  db_schema: <SOURCE_DB_SCHEMA>

templates:
  - <TEMPLATE_NAME>
  - <TEMPLATE_NAME_2>
  - <TEMPLATE_NAME_3>

storage:
  container: <STORAGE_CONTAINER>

  paths:
    raw: <RAW_PATH>
    standard: <STANDARD_PATH>
    quarantine: <QUARANTINE_PATH>

data_quality:
  core_fields:
    - <CORE_FIELD_1>
    - <CORE_FIELD_2>
    - <CORE_FIELD_3>
  non_null_fields:
    - <NON_NULL_FIELD_1>
    - <NON_NULL_FIELD_2>
  id_column: <ID_COLUMN>
  geometry_column: <GEOMETRY_COLUMN>

pseudonimization:
  enabled: <ANONYMIZATION_ENABLED>
  text_columns:
      - <TEXT_COLUMN_1>
  geometry_columns:
    - <GEOMETRY_COLUMN_1>

dmd:
  asset_name_prefix: <ASSET_NAME_PREFIX>
  code_reference_prefix: <CODE_REFERENCE_PREFIX>
  origin_id: <ORIGIN_ID>
  consumer_application_id: <CONSUMER_APPLICATION_ID>
  main_hierarchy_parent: <MAIN_HIERARCHY_PARENT_ID>
  batch_size: <BATCH_SIZE>

quality_threshold:
  max_quarantine_ratio: <MAX_QUARANTINE_RATIO>